### ISSUE TITLE
patchtron quits immediately in Arch Linux

### ISSUE THREAD

**Issue by evbogue** [mmckegg/patchtron#4]
Hey @mmckegg,

I cloned down `patchtron` today, but it seems to quit out on me right away. 

My process was 

```
npm install
npm start
```

Electron launches, and I saw the Patchtron interface for around seven seconds. Then it just quits with no errors? 

Here's what I see in my console

```
[ev@arch patchtron]$ npm start
npm info it worked if it ends with ok
npm info using npm@5.5.1
npm info using node@v8.9.1
npm info lifecycle Patchtron@4.0.0-pre1~prestart: Patchtron@4.0.0-pre1
npm info lifecycle Patchtron@4.0.0-pre1~start: Patchtron@4.0.0-pre1

> Patchtron@4.0.0-pre1 start /home/ev/patchtron
> electron run.js --friends.hops 2

starting scuttleshell
loading custom plugins:  /home/ev/patchtron/sbot-plugin
npm info lifecycle Patchtron@4.0.0-pre1~poststart: Patchtron@4.0.0-pre1
npm info ok
```

I'm not node@8.9.1 and npm@5.5.1

**Comment by evbogue** [comment]
I should mention that I had no other sbots running.

**Comment by evbogue** [comment]
more info

```
Error: could not connect to sbot
    at /home/ev/patchtron/node_modules/ssb-client/index.js:93:23
    at next (/home/ev/patchtron/node_modules/multiserver/compose.js:24:14)
    at /home/ev/patchtron/node_modules/multiserver/compose.js:34:9
    at _cb (/home/ev/patchtron/node_modules/multiserver/plugins/shs.js:28:20)
    at /home/ev/patchtron/node_modules/secret-handshake/protocol.js:115:22
    at /home/ev/patchtron/node_modules/pull-handshake/index.js:10:5
    at Object.abort (/home/ev/patchtron/node_modules/pull-handshake/index.js:35:9)
    at abort (/home/ev/patchtron/node_modules/secret-handshake/protocol.js:35:39)
    at Object.cb (/home/ev/patchtron/node_modules/secret-handshake/protocol.js:50:26)
  Error: stream ended with:64 but wanted:80
    at drain (/home/ev/patchtron/node_modules/pull-reader/index.js:43:26)
    at /home/ev/patchtron/node_modules/pull-reader/index.js:63:18
    at /home/ev/patchtron/node_modules/pull-reader/index.js:20:7
    at drain (/home/ev/patchtron/node_modules/stream-to-pull-stream/index.js:141:18)
    at Socket.<anonymous> (/home/ev/patchtron/node_modules/stream-to-pull-stream/index.js:158:5)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm info lifecycle Patchtron@4.0.0-pre1~poststart: Patchtron@4.0.0-pre1
npm info ok
```

**Comment by mmckegg** [comment]
@evbogue Hmm, strange. I wonder if this is to do with scuttle-shell registering the system tray icon. Have you tried running scuttle-shell standalone and see if it works?
